### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by qodeboy** [pinepain/js-sandbox#10]
Where documentation for this package could be found?

**Comment by pinepain** [comment]
Hi, thanks for bringing this up!

Unfortunately, there is no docs atm. As it said in readme,

> This library is still under heavy development and its public API may change without any warning. Use at your own risk.

so having in mind that public API may be change and facing the risk having them outdating rapidly (as I don't have much time to do it all myself), I decided not to misguide people and come back to docs later.  **However, I'd really appreciate any help here or sponsorship.**

For now you can look into tests and give a brief look at code itself. If you will have any further questions, please, do not hesitate to drop them here as separate issues.

I'll leave this issue opened  to address it later, alike https://github.com/pinepain/php-v8/issues/101.

**Comment by pinepain** [comment]
I'm moving away from PHP world and all my PHP projects going to be abandoned too. Closing this issue as I have no intent to continue working on it unless there would be strong request from community and commercial interest. No more updates or documentation will be made. If someone is interested, feels free to contact me using email specified in my GitHub profile.
